// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_Management.Data;

namespace Student_Management.Migrations
{
    [DbContext(typeof(Student_ManagementContext))]
    [Migration("20210629015037_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Student_Management.Business.Course_Details", b =>
                {
                    b.Property<int>("course_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("course_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("course_ID");

                    b.ToTable("Course_Details");
                });

            modelBuilder.Entity("Student_Management.Business.Student_Details", b =>
                {
                    b.Property<int>("student_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("student_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_ID");

                    b.ToTable("Student_Details");
                });

            modelBuilder.Entity("Student_Management.Business.Student_Enrollment", b =>
                {
                    b.Property<int>("student_Enrollment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Course_Detailscourse_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Student_Detailsstudent_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Tutor_Detailstutor_ID")
                        .HasColumnType("int");

                    b.Property<int>("course_ID")
                        .HasColumnType("int");

                    b.Property<int>("student_ID")
                        .HasColumnType("int");

                    b.Property<int>("tutor_ID")
                        .HasColumnType("int");

                    b.HasKey("student_Enrollment_ID");

                    b.HasIndex("Course_Detailscourse_ID");

                    b.HasIndex("Student_Detailsstudent_ID");

                    b.HasIndex("Tutor_Detailstutor_ID");

                    b.ToTable("Student_Enrollment");
                });

            modelBuilder.Entity("Student_Management.Business.Tutor_Details", b =>
                {
                    b.Property<int>("tutor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tutor_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tutor_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tutor_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tutor_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tutor_ID");

                    b.ToTable("Tutor_Details");
                });

            modelBuilder.Entity("Student_Management.Business.Student_Enrollment", b =>
                {
                    b.HasOne("Student_Management.Business.Course_Details", "Course_Details")
                        .WithMany()
                        .HasForeignKey("Course_Detailscourse_ID");

                    b.HasOne("Student_Management.Business.Student_Details", "Student_Details")
                        .WithMany()
                        .HasForeignKey("Student_Detailsstudent_ID");

                    b.HasOne("Student_Management.Business.Tutor_Details", "Tutor_Details")
                        .WithMany()
                        .HasForeignKey("Tutor_Detailstutor_ID");

                    b.Navigation("Course_Details");

                    b.Navigation("Student_Details");

                    b.Navigation("Tutor_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
